name: hr_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  popover: ^0.3.1
  intl: ^0.20.2
  http: ^1.2.0
  pdf: ^3.11.1
  printing: ^5.13.3
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

  fonts:
    - family: Trap
      fonts:
        - asset: assets/fonts/Trap-Regular.otf
        - asset: assets/fonts/Trap-Light.otf
          weight: 300
        - asset: assets/fonts/Trap-Medium.otf
          weight: 500
        - asset: assets/fonts/Trap-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Trap-Bold.otf
          weight: 700
        - asset: assets/fonts/Trap-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Trap-Black.otf
          weight: 900
    - family: Alfont
      fonts:
        - asset: assets/fonts/alfont.otf